export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_ERROR = "FETCH_DATA_ERROR";
export const FETCH_DATA_START = "FETCH_DATA_START";
export const FETCH_TOKEN_SUCCESS = "FETCH_TOKEN_SUCCESS";
export const FETCH_TOKEN_GENERATE = "FETCH_TOKEN_GENERATE ";
export const LOGOUT = "LOGOUT";
export const FETCH_USER_GENERATE = "FETCH_USER_GENERATE";
export const FETCH_MESSAGE = "FETCH_MESSAGE"